spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/facturx
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update