name: CI

on:
  push:
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate Docker Compose
        run: docker compose config -q

      - name: Build Docker images
        run: docker compose build
      
      - name: Start containers
        run: docker compose up -d
        
      - name: show backend logs 
        run: docker compose logs backend
      - name: Test backend healthcheck
        run: |
          for i in {1..20}; do
            if curl --fail http://localhost:8080/api/healthcheck; then
              echo "Backend healthcheck passed"
              exit 0
            fi

            echo "Backend not ready yet..."
            sleep 3
          done

          echo "Backend healthcheck failed"
          docker compose logs backend
          exit 1

      - name: Stop containers
        if: always()
        run: docker compose down